from tkinter import *
from tkinter.ttk import *
root =Tk()
root.geometry("655x333")
root.title("Anurag Singh")
def getvals():
    name=uservalue.get()
    a=marks1value.get()
    b=marks2value.get()
    c=marks3value.get()
    percentage=(a+b+c)/3
    print(percentage)
    lb = Label(root, text=f"percentage of {name} is {percentage}")
    lb.grid(column=1, row=8)
name=Label(root, text="name")
name.grid(row=0,column=0)
uservalue=StringVar()
userentry=Entry(root,textvariable=uservalue)
userentry.grid(row=0,column=1)
selected = IntVar()
rad1 = Radiobutton(root,text='Male', value=1, variable=selected)
rad2 = Radiobutton(root,text='Female', value=2, variable=selected)
rad1.grid(column=0, row=1)
rad2.grid(column=1, row=1)
Qualification =Label(root, text="Qualification ")
Qualification .grid(row=2,column=0)
combo = Combobox(root)
combo['values']= ("Graduate","Post Graduate")
combo.current(1) 
combo.grid(column=1, row=2)

marks1=Label(root, text="marks1")
marks1.grid(row=3,column=0)
marks1value=IntVar()
marks1entry=Entry(root,textvariable=marks1value)
marks1entry.grid(row=3,column=1)

marks2=Label(root, text="marks2")
marks2.grid(row=4,column=0)
marks2value=IntVar()
marks2entry=Entry(root,textvariable=marks2value)
marks2entry.grid(row=4,column=1)

marks3=Label(root, text="marks3")
marks3.grid(row=5,column=0)
marks3value=IntVar()
marks3entry=Entry(root,textvariable=marks3value)
marks3entry.grid(row=5,column=1)
Button(text="submit", command=getvals).grid(row=6,column=0)

root.mainloop()